---

- name: install influxdb
  include: install_influxdb_yum.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - influxdb-install

- name: config influxdb
  include: config_influxdb.yml
  tags:
    - influxdb-config

- name: make sure influxd is started
  systemd: name=influxdb state=started

- name: execute influx command
  shell: influx -execute 'create database spark'