---

- name: install spark
  hosts: spark
  remote_user: "{{ user }}"
  roles:
    - spark
  tags:
    - spark

- name: install zeppelin
  hosts: spark
  remote_user: "{{ user }}"
  roles:
    - zeppelin
  tags:
    - zeppelin

- name: install notebook
  hosts: notebook
  remote_user: "{{ user }}"
  roles:
    - notebook
  tags:
    - notebook