---

- name: config hibench
  template: src={{ item }} dest={{ install_dir }}/HiBench/conf/{{ item | basename | regex_replace('\.j2','') }}
  with_items:
    - hadoop.conf.j2
    - spark.conf.j2

- name: create data dir
  file: dest={{ data_dir }}/windjammer state=directory recurse=yes
    owner={{ user }} group={{ group }} mode=0755