# hadoop
[hadoop-master]
windjammer

[hadoop-slave]
#wj-05
windjammer

[hadoop:children]
hadoop-master
hadoop-slave

[spark]
windjammer

[zetascale]
windjammer

[hibench]
windjammer

[postgres]
windjammer

[influxdb]
windjammer

[maven]
windjammer

[cmake:children]
maven

[collectd]
windjammer

[grafana]
windjammer

[jdk]
windjammer

[notebook]
windjammer

[other]
windjammer