# hadoop
[hadoop-master]
wj-06

[hadoop-slave]
#wj-05
wj-06

[hadoop:children]
hadoop-master
hadoop-slave

[spark]
wj-05

[zetascale]
wj-[04:06]

[hibench]
wj-05

[postgres]
wj-05

[influxdb]
wj-05

[maven]
wj-05

[cmake:children]
maven

[collectd]
wj-06

[grafana]
wj-05

[jdk]
wj-06

[other]
wj-06