# hadoop
[hadoop-master]
wj-01

[hadoop-slave]
#wj-05
wj-01

[hadoop:children]
hadoop-master
hadoop-slave

[spark]
wj-01

[zetascale]
wj-[04:06]

[hibench]
wj-05

[postgres]
wj-01

[influxdb]
wj-01

[maven]
wj-01

[cmake:children]
maven

[collectd]
wj-01

[grafana]
wj-01

[jdk]
wj-01

[notebook]
wj-01

[other]
wj-01