# hadoop
[hadoop-master]
wj-04

[hadoop-slave]
wj-04
wj-05
wj-06

[hadoop:children]
hadoop-master
hadoop-slave

[spark]
wj-04

[hibench]
wj-04

[postgres]
wj-05

[influxdb]
wj-06

[maven]
wj-04

[collectd-client]
wj-[04:06]

[collectd-server:children]
influxdb