---

hadoop_version: 2.7.3

#download_hadoop_url: http://www-us.apache.org/dist

hadoop_mode: local

hadoop_dfs_datanode_data_dir: [ "/data/hadoop/dfs" ]
hadoop_dfs_replication: 1
hadoop_dfs_blocksize: 268435456

hadoop_yarn_nodemanager_local_dirs: [ "/data/hadoop/yarn" ]
# only be true the first time
hadoop_bootstrap: True

hadoop_yarn_nodemanager_resource_memory_mb: 28000   # < max_memory * 0.8
hadoop_yarn_nodemanager_resource_cpu_vcores: 28   # 实际的cpu core thread - 4