---

- include: install_spark.yml

- include: config_postgre.yml
  when: spark_init_hive_jdbc
  tags:
    - spark-config

- name: config spark
  template: src={{ item }} dest={{ install_dir }}/spark/conf/{{ item | basename | regex_replace('\.j2','') }}
  with_items:
    - spark-env.sh.j2
    - spark-defaults.conf.j2
    - hive-site.xml.j2
#    - metrics.properties.j2
  tags:
    - spark-config

- name: mkdir for spark event log
  command: chdir={{ install_dir }}/hadoop ./bin/hdfs dfs -mkdir -p /spark/eventlog
  tags:
    - spark-config